create table if not exists public.alumni (
  id bigint generated by default as identity primary key,
  usn text unique,
  name text not null,
  email text unique,
  phone text,
  course text,
  department text,
  graduation_year integer,
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_alumni_updated_at on public.alumni;

create trigger set_alumni_updated_at
before update on public.alumni
for each row
execute function public.set_updated_at();
